# Generated by Django 5.1.1 on 2024-09-13 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credit",
            name="grades",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="credit",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="credit",
            name="credit",
            field=models.CharField(max_length=200),
        ),
    ]
