# Generated by Django 5.1.1 on 2024-09-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_credit_created_credit_grades_credit_updated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credit",
            old_name="grades",
            new_name="desc",
        ),
    ]
