# Generated by Django 5.1.1 on 2024-09-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_desc"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Desc",
        ),
    ]
