# Generated by Django 5.1.1 on 2024-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_delete_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="electrical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coarse", models.CharField(max_length=200)),
                ("credit", models.IntegerField()),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="credit",
            name="desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
