# Generated by Django 5.1.1 on 2024-09-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_civil_mechanical_metallugy_quantinty"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quantinty",
            new_name="Quantity",
        ),
    ]
