# Generated by Django 5.1.1 on 2024-09-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_rename_quantinty_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mechanical",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="metallugy",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="quantity",
            name="credit",
        ),
        migrations.AddField(
            model_name="mechanical",
            name="desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="metallugy",
            name="desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="quantity",
            name="desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
