# Generated by Django 5.1.1 on 2024-09-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_remove_mechanical_credit_remove_metallugy_credit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mechanical",
            old_name="desc",
            new_name="credit",
        ),
    ]
