# Generated by Django 5.1.1 on 2024-09-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_mechanics"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Metallugy",
            new_name="Mechanic",
        ),
    ]
