# Generated by Django 5.1.1 on 2024-09-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_rename_metallugy_mechanic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mechanics",
            new_name="Metallugy",
        ),
    ]
