# Generated by Django 5.1.1 on 2024-09-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_chemical_industrial_textile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credit",
            old_name="desc",
            new_name="description",
        ),
    ]
