# Generated by Django 5.1.1 on 2024-09-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_rename_desc_credit_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credit",
            old_name="description",
            new_name="desc",
        ),
    ]
